ChildMindInstitute/mindlogger-web-refactor

src/i18n/en/translation.json, src/i18n/fr/translation.json, src/pages/RecoveryPassword/index.tsx
resolves: [M2-4826](https://mindlogger.atlassian.net/browse/M2-4826)
Update message when user tries to use an invalid/expired link to recover password
API endpoint: `/users/me/password/recover/healthcheck`
[M2-4826]: https://mindlogger.atlassian.net/browse/M2-4826?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> M2-4826: Update forgot password expired/invalid link message

src/entities/activity/lib/helpers.test.ts, src/entities/activity/lib/helpers.ts, src/entities/activity/lib/types/item.ts, src/entities/activity/ui/ActivityCardItem.tsx, src/entities/activity/ui/AdditionalTextResponse.tsx, src/entities/activity/ui/index.ts, src/entities/applet/model/hooks/useSaveActivityItemAnswer.ts, src/entities/applet/model/hooks/useUserEvents.ts, src/entities/applet/model/mapper.ts, src/entities/applet/model/slice.ts, src/entities/applet/model/types.ts, src/i18n/en/translation.json, src/i18n/fr/translation.json, src/shared/api/services/axios.ts, src/shared/api/types/item.ts, src/widgets/ActivityDetails/model/hooks/useAutoForward.ts, src/widgets/ActivityDetails/model/mappers.ts, src/widgets/ActivityDetails/model/validateItem.ts, src/widgets/ActivityDetails/ui/AssessmentPassingScreen.tsx
resolves: [M2-4833](https://mindlogger.atlassian.net/browse/M2-4833)
This PR adds an additional text response field in the respondent web app, for those items that support it:
- Single Selection
- Multiple Selection
- Slider
- Date
- Time
- Time Range
- Audio Player
> [!NOTE]
> There are some items missing, and some present that are not even supported in the web app yet. I just added support based on the items that are represented in the codebase.
The PR covers these criteria:
- When an item type that allows an additional text response is presented to the respondent, clearly display a text input field where they can enter their response. 
- Require the user to provide an additional text response when the item type is configured to require it. Respondents will not be able to move to the …
=> [M2-4833] Feature: Additional text response

src/entities/applet/model/mapper.ts, src/shared/ui/Items/Date/index.tsx, src/shared/ui/Items/Time/index.tsx
https://mindlogger.atlassian.net/browse/M2-5293
-validating date and time items values before passing to activityProgress
-timeRange item related bug fixes
=> M2-5293: validating date and time items values before passing to activityProgress, bug fixes

src/entities/applet/model/hooks/useSaveActivityItemAnswer.ts, src/widgets/ActivityGroups/ui/ActivityCard/ActivityCardBase.tsx, src/widgets/Footer/index.tsx
📝 Description
🔗 [Jira Ticket M2-5011](https://mindlogger.atlassian.net/browse/M2-5011)
I`ve changed year in the footer section. It was 2023, it is 2024.
📸 Screenshots
🪤 Peer Testing
Example test step:
Start up the API and the webapp
Open any page in desktop mode
Expected outcome: The 2024 year should appears in the footer section
✏️ Notes
=> M2-5011 Feature: Update year in the footer

src/widgets/ActivityDetails/ui/AssessmentPassingScreen.tsx
🔗 [Jira Ticket M2-5303](https://mindlogger.atlassian.net/browse/M2-5303)
In this PR I resolve the issue with the Submit Popup. The problem is when the user has no ability to go back the modal popup should hide the description.
This PR changes:
- Submit popup
- yarn
- yarn dev
- Open the http://localhost:5173 (or any another port that you use for host your local app)
- Login
- Open any applet
- Open any activity that has the following settings (Ability to change user answer = false OR Remove back button = true)
- Pass the activity
- Click submit button
- Have a look at the submit popup
=> M2-5203 Fix: Submit popup text

src/features/RecoveryPassword/ui/RecoveryPasswordForm.tsx, src/i18n/en/translation.json, src/i18n/fr/translation.json, src/pages/Login/index.tsx, src/shared/ui/NotificationCenter/lib/useNotification.ts, src/shared/utils/hooks/index.ts, src/shared/utils/hooks/useOnceEffect.ts
🔗 [Jira Ticket M2-4827](https://mindlogger.atlassian.net/browse/M2-4827)
I've redirected the user to the login page after successful password redirection and displayed a success banner on that page. I've also removed the `backToLogin` button, and the form success message.
https://github.com/ChildMindInstitute/mindlogger-web-refactor/assets/14842108/ed8c47e1-7cb5-46b9-b415-4bc940dafb58
Example test step:
- Start up the API and the webapp
- Navigate to the web app landing page
- Click the forgot password link
- Enter your email address and click *Get Reset It*
- Click on the link in your email (Go to http://localhost:8025/ for local testing)
- Enter the new password
**Expected outcome:** You should be redirected to the login screen and see a banner displayed for 5 seconds
I'm using `useRef` …
=> M2-4827: Post password reset redirection

.github/pull_request_template.md
🔗 [Jira Ticket M2-5512](https://mindlogger.atlassian.net/browse/M2-5512)
This PR updates the [GitHub pull request description template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates#pull-request-templates) template to an updated format as agreed upon during team's technical talks. 
GitHub will start using this as this repository's pull request template once this is merged to the default branch (`master`).
- an updated PR template
=> M2-5512: updates PR template format

src/shared/constants/routes.ts
resolves: M2-5548
Removed wrong symbol at the end of the path
=> M2-5548 [Web app 2.5] Public link without the required account: error when sending responses for Activity Flow

src/shared/ui/Markdown/lib/markdown-builder.ts, src/shared/ui/Markdown/lib/validateAudio.ts, src/shared/ui/Markdown/style.css
resolves: M2-5015
Recently the WYSIWYG component have no support of Quotes. Now it have.
Also audio files in the WYSIWYG component in Safari browser displays like video. Now it displays correctly.
Before
After
Before
After
=> M2-5015 Message item: Not all formatting options of WYSIWYG component are supported

src/abstract/lib/GroupBuilder/AvailableGroupBuilder.test.ts, src/abstract/lib/GroupBuilder/AvailableGroupEvaluator.ts, src/abstract/lib/GroupBuilder/GroupUtility.ts, src/abstract/lib/GroupBuilder/ScheduledGroupEvaluator.test.ts, src/entities/event/model/operations/ScheduledDateCalculator.monthly.test.ts, src/entities/event/model/operations/ScheduledDateCalculator.ts
resolves: M2-5060
Monthly events are not displayed in the web app if the last date of the last day of the month does not match the date of the event installation
=> M2-5060 Change logic of monthly event calculation

src/shared/constants/theme.ts, src/shared/ui/NotificationCenter/ui/ErrorNotification.tsx, src/shared/ui/NotificationCenter/ui/Notification.tsx, src/shared/ui/NotificationCenter/ui/NotificationAnimation.tsx, src/shared/ui/NotificationCenter/ui/NotificationCenter.tsx, src/shared/ui/NotificationCenter/ui/SuccessNotification.tsx, src/shared/ui/NotificationCenter/ui/WarningNotification.tsx, src/shared/utils/hooks/index.ts, src/shared/utils/hooks/useIntersectionObserver.ts
resolves: M2-5266
User unable to see notification container at the screen after scrolling to the bottom.
=> [M2-5266] Changed the notification center behavior

src/shared/ui/Markdown/lib/extractDataFromMediaLink.ts, src/shared/ui/Markdown/lib/markdown-builder.ts, src/shared/ui/Markdown/lib/useMarkdownExtender.ts
🔗 [Jira Ticket M2-3437](https://mindlogger.atlassian.net/browse/M2-3437)
We have a clear format of the media link. It looks like "![file_name](file_url)". To extract the params from the link we use regex. And in the ticket 3437, the tester team found the edge case when the regex works incorrectly.
- Class MarkdownExtender
=> [M2-3437] Change the regex for extracting params from media link

.github/workflows/update-jira-tickets.yaml
🔗 [Jira Ticket M2-5923](https://mindlogger.atlassian.net/browse/M2-5923)
This PR introduces a GitHub Actions workflow that submits a list of ticket numbers to a Jira webhook based on a number of factors.
The workflow is triggered by a GitHub release, and it collates the list of Jira ticket numbers that were worked on since the last GitHub release that had a successful Jenkins build. It then waits for the outcome of the current build (trigged by the release) and submits that list of Jira tickets if the build is successful.
My original approach to this ticket was to modify the Jenkins scripts, but I changed that because it's much simpler to have this logic in one workflow (instead of being split across multiple CodeCommit repos), and we eventually intent to move CI/CD to GitHub Actions …
=> M2-5923: Create Update Jira Tickets GitHub Actions workflow

.github/workflows/update-jira-tickets.yaml
🔗 [Jira Ticket M2-5923](https://mindlogger.atlassian.net/browse/M2-5923)
This PR follows up #422 by changing the release event type to `published` instead of `created`. The `created` event type doesn't capture releases that were previously saved as draft, so some releases would be missed.
This change also brings the workflow file to the dev branch. This is important because that's where the tagging takes place and the workflow file won't be triggered if it doesn't exist on that branch.
=> M2-5923: Fix release event type

src/entities/applet/model/mapper.ts
🔗 [Jira Ticket M2-6191](https://mindlogger.atlassian.net/browse/M2-6191)
Single Selection per Row' item: Option ID is displaying instead of the response value in the 'activity_user_journey.csv' file.
I have extended the mapper for the saveSetUserEvent method.
=> [M2-6191] Bug: Single Selection per Row' item: Option ID is displaying instead of the response value in the 'activity_user_journey.csv' file

src/entities/activity/ui/items/Matrix/MatrixMultiSelectItem/CheckboxButton.tsx, src/entities/activity/ui/items/Matrix/MatrixSingleSelectItem/RadioButton.tsx, src/shared/ui/Items/SelectBase/SelectBaseBox.tsx, src/shared/ui/Items/SelectBase/SelectBaseText.tsx
🔗 [Jira Ticket M2-6237](https://mindlogger.atlassian.net/browse/M2-6237)
Previously I have reused the SelectBaseBox as a wrapper for Single and Multi selection components. Since I have added matrix items I started reusing the SelectBaseBox for this as well. And for different components should be different behavior. I added the "flex" property to the wrapper.
- SelectBaseBox
=> [M2-6237] Add the flex property for SelectBaseBox component

.github/workflows/update-jira-tickets.yaml
This PR updates the Update Jira Tickets GH Actions workflow to fetch all commits before determining JIRA tickets. 
The current behavior is only using the most recent commit on the branch because the checkout action does a shallow clone by default. Therefore, we have to unshallow the clone in order to get all the commit messages. I decided to do it this way, instead of doing a deep clone from the outset because there are several exit points for the job that would render the deep clone unnecessary. So I do it at the point where it's needed
Compare the results of [the most recent release run](https://github.com/ChildMindInstitute/mindlogger-web-refactor/actions/runs/8660519735/job/23748618273#step:7:17) to [this manual run](https://github.com/ChildMindInstitute/mindlogger-web-refactor/actions …
=> Update Jira Tickets 2

src/features/TransferOwnershipAccept/ui/TransferOwnershipAccept.tsx, src/features/TransferOwnershipDecline/ui/TransfetOwnershipDecline.tsx, src/shared/ui/CardItem/CardItem.tsx, src/shared/ui/DisplaySystemMessage/index.tsx, src/shared/ui/Items/SelectBase/SelectBaseText.tsx, src/widgets/ActivityGroups/ui/ActivityGroupList.tsx
🔗 [Jira Ticket M2-6239](https://mindlogger.atlassian.net/browse/M2-6239)
The root issue was an incorrect property name. The data-testid property was provided for the Text component instead of the correct one.
=> [M2-6239] Missing data-testid attributs for some elements starting from v2.1.7

src/entities/activity/ui/items/Matrix/Slider/index.tsx
🔗 [Jira Ticket M2-6292](https://mindlogger.atlassian.net/browse/M2-6292)
The onHandleChange method for the SliderRow item had the incorrect logic of updating the current values. The bug appears when you have tried to choose the value for the first time. The first try was ignored. Now it works correctly.
=> [M2-6292] Fix the onHandleChange for the SliderRows item

src/features/TakeNow/ui/ValidateTakeNowParams.tsx, src/shared/api/types/activity.ts, src/widgets/ActivityDetails/model/hooks/useAnswers.ts
🔗 [Jira Ticket M2-6044](https://mindlogger.atlassian.net/browse/M2-6044)
This PR updates the code that submits the activity responses to `/answers` to include the values for `target_subject_id` and `source_subject_id`. The values are only included if the `enableMultiInformant` feature flag is enabled.
N/A
> [!NOTE]
> This feature depends on the `enableMultiInformant` feature flag. If it it not already enabled, you can manually enable it [here](https://github.com/ChildMindInstitute/mindlogger-web-refactor/blob/9ec96b45196bf8f1eb377850d8d225e51323b559/src/shared/utils/hooks/useLaunchDarkly.ts#L22-L30) like so:
>
> `features.enableMultiInformant = true;`
> [!NOTE]
> There's an in-progress API patch that this PR depends on. If https://github.com/ChildMindInstitute/mindlogger-backend-refactor/p …
=> M2-6044: Submit Take Now Params

src/abstract/lib/types/multiInformant.ts, src/entities/applet/model/hooks/useMultiInformantState.ts, src/entities/applet/model/types.ts, src/features/TakeNow/lib/useTakeNowValidation.tsx, src/features/TakeNow/ui/MultiInformantBadge.tsx, src/features/TakeNow/ui/MultiInformantBadgeTile.tsx, src/features/TakeNow/ui/ValidateTakeNowParams.tsx, src/features/TakeNow/ui/index.ts, src/widgets/ActivityDetails/model/hooks/useAnswers.ts, src/widgets/ActivityDetails/ui/AssessmentLayoutHeader.tsx
🔗 [Jira Ticket M2-6109](https://mindlogger.atlassian.net/browse/M2-6109)
This PR creates a `MultiInformantBadge` component that is shown during the completion of an activity in a multi-informant context. The component displays itself when the following are true:
- The `enableMultiInformant` feature flag is turned on
- The multi-informant state has been set. This state is set during the validation of multi-informant parameters in the `ValidateTakeNowParams` component.
> [!NOTE]
> This feature depends on the `enableMultiInformant` feature flag. If it it not already enabled, you can manually enable it [here](https://github.com/ChildMindInstitute/mindlogger-web-refactor/blob/9ec96b45196bf8f1eb377850d8d225e51323b559/src/shared/utils/hooks/useLaunchDarkly.ts#L22-L30) like so:
>
> …
=> M2-6109: [FE] [Web App] Header - Update to Include Subject and Respondent

src/features/TakeNow/ui/MultiInformantBadgeTile.tsx, src/features/TakeNow/ui/TakeNowSuccessModal.tsx, src/i18n/en/translation.json, src/i18n/fr/translation.json, src/shared/ui/MuiModal/index.tsx, src/widgets/ActivityDetails/model/hooks/useEntityComplete.ts, src/widgets/ActivityGroups/ui/ActivityGroups.tsx
🔗 [Jira Ticket M2-6272](https://mindlogger.atlassian.net/browse/M2-6272)
This ticket implements a success modal that displays itself at the end of the Take Now flow. It presents a choice to the logged-in user of returning to the admin app, or staying in the web app.
https://github.com/ChildMindInstitute/mindlogger-web-refactor/assets/14842108/6420be0d-6441-4d33-abab-f7b3b9029fcc
https://github.com/ChildMindInstitute/mindlogger-web-refactor/assets/14842108/a1957338-0e63-4746-8aef-dd601154cf78
> [!NOTE]
> You will need to launch the take now flow from the admin app
You will need a workspace with the following:
- an owner
- a limited account participant
- an applet with a single activity
- Sign in to the participant web app as the owner
- Complete an activity within an applet and submit the …
=> M2-6272: [FE] [Web App] Take Now - After Submit - Provide Success Message

src/entities/applet/model/hooks/useMultiInformantState.ts, src/entities/applet/model/slice.ts, src/features/TakeNow/ui/ValidateTakeNowParams.tsx, src/widgets/ActivityDetails/model/hooks/useAnswers.ts, src/widgets/ActivityGroups/ui/ActivityGroups.tsx
🔗 [Jira Ticket M2-6534](https://mindlogger.atlassian.net/browse/M2-6534)
This PR fixes the blank page bug encountered when a user with existing Redux state tries to initiate an activity outside of both the multi-informant flow and the proper feature flagged context.
N/A
To reproduce the issue, follow these steps on the `release/v2.1.9` branch:
- Check out the a4970aae0470e4b0164871fe3cba08f457e64fe7 revision
- Install dependencies with `yarn`
- Start the vite server and load the respondent web app
- Clear application data in dev tools and refresh the page
- Log in to the app and complete an activity
- Stop the vite server (keep the browser window open)
- Check out the ac7c5639e1f071ecd12eb8b65125d626169abb56 revision
- Install dependencies with `yarn`
- Start the vite server
- Log in to …
=> bugfix: 🔥[Web app] The blank page is displaying in web app if start an Activity execution (M2-6534)

src/features/PassSurvey/hooks/useSummaryData.ts
The guard was added before accessing the store to make applications reliable when the user has an old version of the store
=> [No-task] The guard was added before access to store

src/entities/applet/model/integrations/LorisAppletIntegration.ts
The web app gets crashed while the user uses take now. The basic guard was added to avoid access to no existance part of state
=> [No-task] The basic guard was added to LorisAppletIntegration

src/features/TakeNow/lib/TakeNowParams.types.ts, src/features/TakeNow/lib/useTakeNowValidation.tsx, src/features/TakeNow/ui/ValidateTakeNowParams.tsx, src/pages/AppletDetailsPage/index.tsx
🔗 [Jira Ticket M2-6480](https://mindlogger.atlassian.net/browse/M2-6480)
This PR updates the validation logic for the take now flow by allowing a source subject ID to be specified, instead of defaulting to the subject ID of the logged in user.
Consequently, the multi-informant badge now shows the provided source subject as the respondent
>[!NOTE]
> This badge is replaced in https://github.com/ChildMindInstitute/mindlogger-web-refactor/pull/460
N/A
Follow the testing steps in https://github.com/ChildMindInstitute/mindlogger-admin/pull/1728
N/A
=> feat(mi): Update take now validation logic (M2-6480)

src/entities/answer/api/index.ts, src/entities/answer/api/useValidateMultiInformantAssessmentQuery.ts, src/entities/answer/index.ts, src/features/TakeNow/lib/useTakeNowValidation.tsx, src/i18n/en/translation.json, src/i18n/fr/translation.json, src/shared/api/services/answer.service.ts, src/shared/api/services/index.ts, src/shared/api/types/answer.ts, src/widgets/ActivityGroups/ui/ActivityCard/index.tsx
🔗 [Jira Ticket M2-6746](https://mindlogger.atlassian.net/browse/M2-6746)
🔗 [Jira Ticket M2-6856](https://mindlogger.atlassian.net/browse/M2-6856)
This PR adds the `useValidateMultiInformantAssessmentQuery` query, which is based on the `/answers/applet/{applet_id}/multiinformant-assessment/validate` API endpoint implemented in https://github.com/ChildMindInstitute/mindlogger-backend-refactor/pull/1316. This moves the majority of the take-now parameter validation to the API instead of being done solely on the frontend.
There is no functional difference between the two implementations, so you may refer to https://github.com/ChildMindInstitute/mindlogger-admin/pull/1728 for testing guidance
N/A
Please refer to https://github.com/ChildMindInstitute/mindlogger-admin/pull/1728 (specifically the …
=> feat(mi): Consume API take now validation endpoint (M2-6746) (M2-6856)

src/features/TakeNow/lib/useTakeNowValidation.tsx, src/features/TakeNow/ui/ValidateTakeNowParams.tsx, src/i18n/en/translation.json, src/i18n/fr/translation.json
🔗 [Jira Ticket M2-6667](https://mindlogger.atlassian.net/browse/M2-6667)
This PR adds an extra error message (`mismatchedRespondent`) to be shown in case the take now `respondentId` does not match the ID of the currently logged-in user. 
The error message it replaces (`invalidRespondent`) is currently shown in 4 scenarios:
- Respondent/logged-in user mismatch (the scenario this ticket addresses)
- Logged-in user is not an owner/manager
- Logged-in user does not have permission to provide answers to the applet
- Logged-in user does not have permission to fetch the details of the source/target subjects
That error message continues to be shown in those other scenarios
1. Initiate the take now flow in the respondent web app with an invalid `respondentId` value.
2. Observe the error message …
=> feat(mi): Update mismatched respondent error message copy (M2-6667)

src/features/PassSurvey/ui/StartAssessmentButton.tsx, src/widgets/ActivityDetails/ui/AssessmentPassingScreen.tsx
🔗 [Jira Ticket M2-6778](https://mindlogger.atlassian.net/browse/M2-6778)
No Summary screen after flow execution if the checkbox "Show Score Summary" is disabled in at least one activity in the flow
- onSuccessSubmit handler
=> No Summary screen after flow execution if the checkbox "Show Score Summary" is disable in at least one activity in the flow(fix:M2-6778) 

src/shared/ui/Banners/Banner/Banner.test.tsx, src/shared/ui/Banners/Banner/Banner.tsx, src/shared/ui/Banners/Banners.test.tsx
🔗 [Jira Ticket M2-6987](https://mindlogger.atlassian.net/browse/M2-6987)
This change fixes a regression identified when migrating from Notifications infra to Banners (#477) where markdown passed to the Banner component was not properly converted to rich text.
| Before                      | After                                 |
| -------------------------------------- | ------------------------------------- |
| <img width="459" alt="Screenshot 2024-06-11 at 3 01 43 PM" src="https://github.com/ChildMindInstitute/mindlogger-web-refactor/assets/1282772/1a4291b0-0f79-476b-bb1c-0e8025741600"> | <img width="429" alt="Screenshot 2024-06-11 at 3 01 55 PM" src="https://github.com/ChildMindInstitute/mindlogger-web-refactor/assets/1282772/c77aaa53-b197-4473-a070-6b2a9ba3691d"> |
- Log into the Web …
=> fix: restore support for markdown in banners (M2-6987)

src/features/TakeNow/lib/useTakeNowValidation.tsx, src/shared/api/types/applet.ts
Replaces how we obtain the workspace ID (`owner_id`) to use the new value from `/applets/{applet_id}` instead of using `encryption.account_id`
🔗 [Jira Ticket M2-6948](https://mindlogger.atlassian.net/browse/M2-6948)
Ensure your local backend is using this branch https://github.com/ChildMindInstitute/mindlogger-backend-refactor/pull/1402
- Initiate TakeNow from Admin
- Log in to web app
- TakeNow should complete correctly
Merging blocked until BE PR is merged
=> fix(mi): update ownerId for TakeNow (M2-6948)

src/features/TakeNow/lib/TakeNowParams.types.ts, src/features/TakeNow/lib/types.ts, src/features/TakeNow/lib/useTakeNowValidation.tsx, src/features/TakeNow/ui/ValidateTakeNowParams.tsx, src/i18n/en/translation.json, src/i18n/fr/translation.json
🔗 [Jira Ticket M2-6844](https://mindlogger.atlassian.net/browse/M2-6844)
This PR updates the behaviour of the "mismatched respondent" take now validation scenario. The current behaviour shows an error message instructing the admin user to log out, log back in as the correct user, and re-initiate take now from the admin app
The updated behaviour automatically logs the admin out, and shows a persistent error message instructing them to log in as the correct user to initiate take now. The multi-informant take now context is retained in the tab as long as it remains open.
- Construct a take-now URL in the following format: `https://localhost:5173/protected/applets/{appletId}?startActivityOrFlow={activityId}&sourceSubjectId={sourceSubjectId}&targetSubjectId={targetSubjectId}&respondentId={rando …
=> Log the admin out if there is a mismatched respondent ID

src/widgets/Survey/model/validateItem.ts, src/widgets/Survey/ui/PassingScreen.tsx, src/widgets/Survey/ui/index.tsx
🔗 [Jira Ticket M2-7014](https://mindlogger.atlassian.net/browse/M2-7014)
A regression was introduced with the transition from `Notifications` to `Banners`: while taking an activity, if the step failed validation to proceed to the next step, then you corrected the issue and proceeded successfully, the stale warning would linger even adjacent to a success message. This PR fixes that.
I also noticed that the assessment completion success banner was remaining visible when the next activity was started. I fixed that by clearing all banners when an assessment begins.
https://github.com/ChildMindInstitute/mindlogger-web-refactor/assets/1282772/dbbf7245-6c79-4bea-a322-195876096dfd
> [!NOTE]
> The `metapod` version of the BE is currently not accepting answer submissions with the latest version of …
=> fix: hide warnings when proceeding to next step (M2-7014)

src/shared/utils/analytics/mixpanel.ts
🔗 [Jira Ticket M2-7159](https://mindlogger.atlassian.net/browse/M2-7159)
This change ensures Mixpanel callbacks will work even when Mixpanel is disabled, which @ionyRojas and I think is responsible for the "Return to Admin App" button failing to close the Web App tab after Take Now. 🤞🏻 
1. Comment out these lines in your Web App's `.env` file:
```env
```
2. Perform Take Now in the Admin App, complete the assessment in the Web App, and press the **Return to Admin App** button.
**Expected outcome:** Web App should close, and Admin App should be focused.
=> fix(mi): run Mixpanel callbacks when Mixpanel disabled (M2-7159)

src/abstract/lib/types/multiInformant.ts, src/entities/applet/model/hooks/useMultiInformantState.ts, src/entities/applet/model/slice.ts, src/features/PassSurvey/hooks/useSubmitAnswersMutation.ts, src/features/TakeNow/lib/useTakeNowValidation.tsx, src/features/TakeNow/ui/TakeNowSuccessModal.tsx
🔗 [Jira Ticket M2-7289](https://mindlogger.atlassian.net/browse/M2-7289)
This PR adds the `Submit ID` property to the _Return to Admin App button clicked_ MixPanel event
1. Complete the take now flow
2. Go to https://mixpanel.com/project/3333580/view/3841316/app/events
3. Check for the _Return to Admin App button clicked_ event and confirm that it has a `Submit ID`
N/A
=> fix: Add missing Submit ID to MixPanel event (M2-7289)

src/app/store.ts, src/entities/banner/model/slice.ts, src/widgets/Survey/ui/PassingScreen.tsx
🔗 [Jira Ticket M2-7281](https://mindlogger.atlassian.net/browse/M2-7281)
This PR updates the success banner shown at the end of an activity to be persistent, requiring user action to dismiss it. This banner previously auto-dismissed after 5s.
I've also taken the opportunity to make the banner infrastructure session-local, which means that banners will no longer persist across tabs.
N/A
1. Complete an activity
2. Confirm that the success banner is shown for more than 5s
3. Navigate to the applets page
4. Confirm that the banner is still present
5. Click the X icon
6. Confirm that the banner is dismissed
1. Complete an activity
2. Observe that the success banner is shown for more than 5s
3. Start a new activity **without** clicking the X icon
4. Click the **Save & exit** button
7. Confirm …
=> feat: Persistent activity success banner (M2-7281)

src/entities/applet/model/hooks/useEntityComplete.ts, src/features/PassSurvey/hooks/useAnswers.ts, src/features/TakeNow/ui/MultiInformantTooltip.tsx, src/pages/AppletDetailsPage/index.tsx, src/shared/utils/types/featureFlags.ts, src/widgets/ActivityGroups/ui/index.tsx
🔗 [Jira Ticket M2-6992](https://mindlogger.atlassian.net/browse/M2-6992)
This PR removes all references to the `enableMultiInformant` and `enableMultiInformantTakeNow` feature flags. The code was modified to assume they are enabled.
N/A
Sanity checks and regression testing.
Specifically the take now flow
N/A
=> refactor: Remove release 1 feature flags (M2-6992)

src/features/PassSurvey/hooks/useStartSurvey.ts, src/widgets/ActivityGroups/model/hooks/useTakeNowRedirect.ts, src/widgets/ActivityGroups/ui/ActivityCard/index.tsx, src/widgets/ActivityGroups/ui/index.tsx
🔗 [M2-7796](https://mindlogger.atlassian.net/browse/M2-7796): [R2][FE][MI Assign] Ensure Take Now takes priority over Assignments
This PR updates how "Take Now" activities/flows are started. Previously, this logic was handled via an effect hook rendered by the `ActivityCard` component, which was rendered as part of the list of activities/flows that appeared on page for the relevant applet.
The addition of activity/flow assignments (gated by the `enableActivityAssign` feature flag), changes the behaviour of this list so that only explicitly assigned activities/flows appear. 
This means that if Take Now was initiated for a respondent subject that did not have that the selected activity or flow assigned, it would fail to start. Additionally, if Take Now was initiated about a specific target …
=> fix: Allow "Take Now" to start when respondent is not explicitly assigned (M2-7796)

src/entities/activity/lib/downloadPhrasalTemplateItem.ts, src/entities/activity/ui/items/ActionPlan/Document.tsx, src/entities/activity/ui/items/ActionPlan/Page.tsx, src/entities/activity/ui/items/PhrasalTemplateItem.tsx
🔗 [Jira Ticket M2-7207](https://mindlogger.atlassian.net/browse/M2-7207)
This PR updates the "download" feature for Action Plan:
* Action Plan cards are now downloaded separately as individual files
* Downloaded images are now JPEG
* Downloaded images now have proper filename formatting
* Images are now downloaded with 3x magnification<sup>1</sup>
* The "download" button now triggers the share dialog on mobile devices<sup>2</sup>
N/A
Preparation
* Create an applet with a phrasal template that's long enough to result in truncation of Action Plan card content
On Desktop browser:
1. Start the applet and continue until the phrasal template step
2. Click the "Download" button
* At this point, the browser should download multiple images as individual JPEG files<sup>3</sup>
On Mobile browser:
1. …
=> feat: action plan download updates (M2-7207)

src/features/PassSurvey/model/ScoresExtractor.ts, src/shared/api/types/activity.ts
🔗 [Jira Ticket M2-8097](https://mindlogger.atlassian.net/browse/M2-8097)
This PR updates the Report Summary screen to omit report scores configured with scoring type `score`. These are scores that are linked to a subscale and are currently not supported as part of the report summary screen.
N/A
> [!NOTE]
> This PR depends on https://github.com/ChildMindInstitute/mindlogger-admin/pull/1935 in order to configure the activity from the admin app
In the admin app
1. Create an activity with a subscale containing a lookup table and an activity item (in its "Elements within Subscale" list)
2. Create a report score and set the score type to "Score"
3. Select the subscale from the dropdown list
4. Create another report score and set the score type to "Raw Score"
5. Save the activity
In the web app …
=> feat: Omit Report Scores with Scoring Type "Score" from the Report Summary Screen (M2-8097)

src/entities/applet/ui/AppletCard.tsx, src/entities/user/model/hooks/useOnLogin.ts, src/features/InvitationAccept/ui/InvitationAcceptButton.tsx, src/features/Login/ui/LoginForm.tsx, src/features/Logout/lib/useLogout.ts, src/features/PassSurvey/hooks/useStartSurvey.ts, src/features/PassSurvey/hooks/useSubmitAnswersMutation.ts, src/features/PrivateJoinAccept/ui/PrivateJoinAcceptButton.tsx, src/features/Signup/ui/SignupForm.tsx, src/features/TakeNow/ui/TakeNowSuccessModal.tsx, src/features/TransferOwnershipAccept/ui/TransferOwnershipAccept.tsx, src/features/TransferOwnershipDecline/ui/TransfetOwnershipDecline.tsx, src/pages/Login/index.tsx, src/shared/utils/analytics/mixpanel.ts, src/shared/utils/analytics/mixpanel.types.ts, src/widgets/ActivityGroups/ui/ActivityCard/index.tsx
This PR modifies the way events are tracked with Mixpanel to match a [similar change](https://github.com/ChildMindInstitute/mindlogger-admin/pull/1959) in the admin repo. There is now a central place to define events and their properties so that we can conveniently see which properties are included in each event, and where they are used.
Now in order to track a new event, you first define it in the event type in the `MixpanelEventType` enum
```typescript
export enum MixpanelEventType {
UpgradeToFullAccountClicked = 'Upgrade to Full Account clicked',
}
```
Then define any extra properties it will need in the `MixpanelProps` enum
```typescript
export enum MixpanelProps {
Via = 'Via',
}
```
Then finally define the event type and add it to the `MixpanelEvent` type union
```typescript
export …
```
=> chore: Mixpanel Refactor

src/abstract/lib/constants.ts, src/entities/activity/ui/items/ActionPlan/ResponseSegment.tsx, src/entities/activity/ui/items/ActionPlan/phrasalData.ts
As an Admin, I want to choose the paragraph item type as a response phrase field so that I can include its contents in my Action Plan. By adding paragraph option to the allowed types on validate_phrasal_templates, the backend can store Activities with PhrasalBuilder Items that contain Parragraph items as elements of the PhraseBuilder item. 
🔗 [Jira Ticket M2-7762](https://mindlogger.atlassian.net/browse/M2-7762)
* Create an activity
* Create and item  of type parragraph inside your activity
* In the same activity create a new item of type phrase builder
* Phrase builder should allow you to choose the newly created paragraph item inside the “Select Item (Response)” dropdown menu.
* Complete an activity from the web application and validate that the parragraph can be …
=> feature: paragraph ItemResponseType for phrase builder response options WEB (M2-7762)

src/entities/user/model/hooks/useOnLogin.ts, src/features/Logout/lib/useLogout.ts, src/pages/AuthorizedRoutes.tsx, src/shared/utils/hooks/useSessionBanners/useSessionBanners.ts
🔗 [Jira Ticket M2-8029](https://mindlogger.atlassian.net/browse/M2-8029)
- Fix to the  `useSessionBanners` hook to ensure that logic such as banner removal only occurs after authorization has changed. Replacing the `useEffect` with `useMemo` should ensure that any side effects that get triggered are due the state of the application once any further auth logic has been resolved.
- Fix to redirecting the user after correct authentication to navigate them to the 'Take Now' route.
Before:
https://github.com/user-attachments/assets/8e5149f7-6291-4c96-956f-b24ef8f725c1
After:
https://github.com/user-attachments/assets/6102dd21-54d2-4405-9fde-5238354dabbe
𝐏𝐫𝐞𝐜𝐨𝐧𝐝𝐢𝐭𝐢𝐨𝐧𝐬:
- Have an applet with at least one Team Member and one Full Account participant.
- Be already logged into the Web App as the …
=> fix: Warning banner & post-login redirect both fail when starting `Take Now` while already logged into Web App as wrong respondent (M2-8029) 

src/features/TakeNow/ui/TakeNowSuccessModal.tsx
🔗 [Jira Ticket M2-8219](https://mindlogger.atlassian.net/browse/M2-8219)
This ticket fixes an incorrect context access that resulted in an undefined dereference (`applet.id`)
https://github.com/user-attachments/assets/c9c6c1cd-496f-401b-943b-f210d6a63a8d
https://github.com/user-attachments/assets/6659d01c-5475-448d-8e4e-5ece94abb4a7
1. Perform a take now assessment and click the return to admin app button
2. Confirm that the tab is closed
N/A
=> fix: The "Return to Admin App" button is not working when starting the activity/flow using "Take Now" (M2-8219)

src/entities/activity/lib/hooks/useTextVariablesReplacer.ts, src/shared/api/types/applet.ts, src/widgets/ActivityGroups/model/hooks/useEntitiesSync.ts
🔗 [Jira Ticket M2-8164](https://mindlogger.atlassian.net/browse/M2-8164)
🔗 [Jira Ticket M2-8026](https://mindlogger.atlassian.net/browse/M2-8026)
In the web app, self-report assessments are identified and tracked using `targetSubjectId === null`. However, for past submissions, the BE returns the raw value of `targetSubjectId`, which is the subject ID of the respondent. These submissions needed to be normalized to have their `targetSubjectId` set to `null`. But for the web app to know which submissions are self-reports, we needed to find out what the subject ID of the respondent (currently logged in user) is for the current applet.
This entailed adding a new `respondentMeta` property to the applet `base_info` endpoint on the BE (https://github.com/ChildMindInstitute/mindlogger-backend-refac …
=> fix: Hide one-time completion self-report assessments after complete (M2-8164, M2-8026)

src/abstract/lib/constants.ts, src/entities/activity/ui/items/ActionPlan/Document.tsx, src/entities/activity/ui/items/ActionPlan/Document.type.ts, src/entities/activity/ui/items/ActionPlan/DocumentContext.ts, src/entities/activity/ui/items/ActionPlan/Page.tsx, src/entities/activity/ui/items/ActionPlan/Phrase.tsx, src/entities/activity/ui/items/ActionPlan/ResponseSegment.tsx, src/entities/activity/ui/items/ActionPlan/TextSegment.tsx, src/entities/activity/ui/items/ActionPlan/hooks.tsx, src/entities/activity/ui/items/ActionPlan/pageComponent.ts, src/entities/activity/ui/items/ActionPlan/pageRenderer.tsx, src/entities/activity/ui/items/ActionPlan/phrasalData.test.ts, src/entities/activity/ui/items/ActionPlan/phrasalData.ts, src/shared/ui/Box/index.tsx
🔗 [Jira Ticket M2-7861](https://mindlogger.atlassian.net/browse/M2-7861)
This PR updates the Action Plan cards rendering code to implement a binary-searched based truncation algorithm. The algorithm will not only truncate at phrasal field level, but also at phrasal field content level, to ensure each card contains the maximum amount of content. Overflowing contents at the end of a card, and corresponding continuation content at the beginning of the following card, are connected by a set of ellipses.
For a walkthrough of implementation detail, please see this loom recording: https://www.loom.com/share/0f3fd7416f814e769ca1318e2ac13a28
**Text Truncation Start**
---
**Text Truncation Both Ends**
---
**Text Truncation End**
---
**List Truncation Start/End **
---
**List Truncation Both Ends** …
=> feat: implement content truncation for Action Plan cards (M2-7861)

.github/workflows/update-jira-tickets.yaml
Whenever a release candidate deployment happens from this repository, a GitHub Actions workflow attempts to process the tickets it contains, and consumes a Jira webhook that triggers an automation to move those tickets into the "To Be Tested" column. I recently updated that automation to also leave a comment on the ticket when the deployment happens
This PR adds more details to the webhook call so that the comment may include more details about the deployment. These details are:
- The release candidate tag
- The repository URL
Once merged here and in the other repositories, I'll update the automation to include these details.
N/A
Due to the external dependency on Jenkins, we won't be able to properlu test this before merging. Please review the code change carefully
N/A
=> chore: Include extra data in call to JIRA webhook

src/entities/activity/ui/items/ActionPlan/pageComponent.ts, src/entities/activity/ui/items/ActionPlan/phrasalData.test.ts, src/entities/activity/ui/items/ActionPlan/phrasalData.ts
🔗 [Jira Ticket M2-8348](https://mindlogger.atlassian.net/browse/M2-8348)
Simplified and fixed logic for generating response text for matrix item types (Single Selection per Row, Multiple Selection per Row). Aligned behaviour with Figma (see 4 examples shown in [this row](https://www.figma.com/design/3wcZ6bxK2QVo733ADxVjBw/SSI-2024?node-id=731-105259&t=M6XInWl55yDqUTtT-4)). Specifically:
- Simply omit data from rows/columns where no selection was made, rather than display "skipped" text
- The order of responses shouldn't change based on the format picked from the dropdown – responses should always be output by column left to right, then by row top to bottom. The only thing that changes based on the format selection is whether to output each response as `columnLabel rowLabel` vs. `rowLabel …
=> fix: Action Plan matrix item type render bugs (M2-8348)

src/entities/activity/ui/items/ActionPlan/phrasalData.test.ts, src/entities/activity/ui/items/ActionPlan/phrasalData.ts
🔗 [Jira Ticket M2-8471](https://mindlogger.atlassian.net/browse/M2-8471)
The Action Plan assumes the Single and Multi selection item type's options have matching index and `value` values. Eg.
```
{
"type": "singleSelect",
"options": [
{
"id": "aad6025b-82f6-4dd1-8409-65ab6f29742f",
"text": "Option A",
"value": 0, // the Admin Panel automatically gives this a value of 0 and places it in the index 0 position of the options array
},
{
"id": "05a34bac-848c-469a-ab7f-60a790520d64",
"text": "Option B",
"value": 1, // the Admin Panel automatically gives this a value of 1 and places it in the index 1 position of the options array
},
{
"id": "307a3dc4-82e8-4894-8aa9-9c68e49ae151",
"text": "Option C",
"value": 2,
}
],
} 
```
However this isn't always the case. If in the Admin Panel the first option …
=> fix: Action Plan not showing correct answer of Single/Multi selection question

src/features/PassSurvey/model/ConditionalLogicValidator.test.ts, src/features/PassSurvey/model/ConditionalLogicValidator.ts, src/shared/api/types/conditionalLogic.ts, src/shared/utils/convert/date/index.ts, src/shared/utils/convert/date/parseDateToMidnightUTC.test.ts, src/shared/utils/convert/date/parseDateToMidnightUTC.ts, src/shared/utils/convert/index.ts, src/shared/utils/convert/time/index.ts, src/shared/utils/convert/time/toHourMinute.test.ts, src/shared/utils/convert/time/toHourMinute.ts
Updates Time/TimeRange/Date item conditional logic validations
🔗 [Jira Ticket M2-8302](https://mindlogger.atlassian.net/browse/M2-8302)
🔗 [Jira Ticket M2-8619](https://mindlogger.atlassian.net/browse/M2-8619)
- Update mismatched TimeRange types
- Update time parse on Greater Than/Less Than/Equal To/Not Equal conditions
- Update date parse on Greater Than/Less Than/Equal To/Not Equal conditions
- Fixes crash when entering TimeRange values
Use the provided applet in the linked amplify environment:
```
Credentials:
user: pr573@example.com
pass: pr573!
```
- Complete the provided Activities for testing Time, Time Range and Date item type conditional logic
- Each activity includes a summary of test cases and expected validations
- Testing the same Applet on the `dev` …
=> fix: Update Time/TimeRange/Date validations (M2-8302)

package.json
Tests related to dates for IFCL were failing due to timezone misalignment. This PR updates the yarn scripts to run in UTC timezone.
🔗 [Jira Ticket M2-8680](https://mindlogger.atlassian.net/browse/M2-8680)
=> test: Update tests script to run with UTC timezone

src/entities/activity/lib/helpers.test.ts, src/entities/activity/lib/types/item.ts, src/features/PassSurvey/model/AnswersConstructService.ts, src/shared/api/types/item.ts
🔗 [Jira Ticket M2-8688](https://mindlogger.atlassian.net/browse/M2-8688)
This change updates function that evaluates what to send to the BE for the response data identifier (`identifier` string), supporting both **Short Text** and, now, **Single Selection** item types. It uses the value from the first item in the activity containing a response identifier, per existing behaviour.
1. Create an activity containing a Single Selection item with **Response Data Identifier** checked. Assign it two options with labels `Option 1` and `Option 2`.
2. Perform an assessment of that activity in the Web App, selecting `Option 1`, and submit your answers.
**Expected outcome:** Answers should be submitted successfully.
3. Perform a second assessment, selecting `Option 2`, and submit your answers. …
=> feat: Submit response data identifier from Single Selection items (M2-8688)

src/features/PassSurvey/model/AnswersConstructService.ts
🔗 [Jira Ticket M2-8780](https://mindlogger.atlassian.net/browse/M2-8780)
When submitting an assessment that includes a **Single Selection** item with **Response Identifier** setting enabled, and an option was chosen after previous options were deleted by the admin, the Response Identifier can be miscalculated, and in fact even result in the Web App causing an error that prevents submission due to out-of-bounds array lookup.
The matching option should have been looked up by `value`, not by array index; this PR fixes that.
The mobile app does option lookup differently since its design is quite different from the web app, and as a result does not have this bug.
1.  Have an applet with an activity and an Single Selection item with the "Response Identifier" setting **checked**.
2.  On that …
=> fix: Response Identifier fix – look up option by `value` not index (M2-8780)

src/app/LaunchDarklyProvider.tsx
This PR focuses on doing a small correction to an environment variable parsing (`VITE_SENTRY_TRACE_PROPAGATION_TARGETS`) that prompted the application to either get stuck in a loading state, or not render anything at all.
The error was shown on console as:
This issue was only spotted after a fresh repo clone/setup, but the fix should cover for any issues related with this, since the parsing of the variable was, in fact, incorrectly done in JS/TS conventions.
=> fix: LaunchDarkly env variable parsing correction

src/app/App.tsx, src/env.d.ts
This changes allows Amplify preview environments to continue to work, which do not have Datadog environment variables set.
- Open the Amplify environment associated with this PR.
**Expected outcome:** Admin App should load normally, without a JS error displayed in DevTools.
=> fix: Prevent app crash with missing DD variables

src/entities/applet/model/hooks/useEntityComplete.ts
There is a delay in between submission and the redirection to an external website. During this delay, the activity start page is shown. The fix introduced is to keep the loading page until we are redirected to Prolific.
🔗 [Jira Ticket M2-8837](https://mindlogger.atlassian.net/browse/M2-8837)
- Removing the activity progress only if we are not in the Prolific Flow
=> fix: activity start page shown on activity submission

src/features/PassSurvey/hooks/useStartSurvey.ts, src/features/PassSurvey/hooks/useSubmitAnswersMutation.ts, src/shared/utils/analytics/mixpanel.types.ts
This PR adds a tracking of prolific events. 3 Events are tracked:
- Assessment Started
- Assessment completed
- Signup Successful
2 Key metrics are sent with those events:
- Prolific PID
- Prolific Study Id
🔗 [Jira Ticket M2-8751](https://mindlogger.atlassian.net/browse/M2-8751)
- User ID cannot be tracked, since the user is anonymous.
=> feat: add events tracking for Prolific

src/entities/applet/model/hooks/useEntityComplete.ts
Participants see cached answers from Study_1 when starting Study_2 if both studies use the same public link, even though they should not. This PR fixes the issue by removing the `activityProgress` of the activity once the user submit their answers.
🔗 [Jira Ticket M2-8918](https://mindlogger.atlassian.net/browse/M2-8918)
=> fix: prolific - cached answers

src/abstract/lib/GroupBuilder/ActivityGroupsBuilder.test.ts, src/abstract/lib/GroupBuilder/AvailableGroupBuilder.test.ts, src/abstract/lib/GroupBuilder/ScheduledGroupEvaluator.test.ts, src/abstract/lib/types/entityProgress.ts, src/entities/applet/model/hooks/useEntityStart.ts, src/entities/applet/model/hooks/useGroupProgressStateManager.ts, src/entities/applet/model/slice.ts, src/entities/applet/model/types.ts, src/entities/event/lib/types/event.ts, src/entities/event/model/mappers.ts, src/features/PassSurvey/hooks/useAnswers.ts, src/features/PassSurvey/hooks/useStartSurvey.ts, src/features/PassSurvey/model/AnswersConstructService.ts, src/shared/api/types/activity.ts, src/shared/api/types/applet.ts, src/shared/api/types/events.ts, src/test/utils/mock.ts, src/widgets/ActivityGroups/model/hooks/useEntitiesSync.ts, src/widgets/ActivityGroups/model/services/ActivityGroupsBuildManager.ts, src/widgets/Survey/model/hooks/useEntityTimer.ts, src/widgets/Survey/ui/PassingScreen.tsx, src/widgets/Survey/ui/WelcomeScreen.tsx
> [!IMPORTANT]
> For the answer submission to be accepted by the BE, it requires running it with this branch checked out: https://github.com/ChildMindInstitute/mindlogger-backend-refactor/pull/1754
🔗 [Jira Ticket M2-8480](https://mindlogger.atlassian.net/browse/M2-8480)
This change adds the `eventHistoryId` property to answer submissions.
1. Create an applet with an activity and an activity flow.
2. Log into the Web App.
3. Open DevTools Network tab.
4. Submit an assessment and observe the payload of the `POST /answers` request:
**Expected outcome:** The JSON object should contain the property `eventHistoryId` with a value in this format: `[event ID]_[version]`.
5. While in DevTools, inspect the most recent result of the `GET /users/me/events/{applet_id}` endpoint and take note of the …
=> feat: Submit `eventHistoryId` in answer data (M2-8480)

src/entities/applet/model/slice.ts
🔗 [Jira Ticket M2-8950](https://mindlogger.atlassian.net/browse/M2-8950)
This is a hotfix for a regression introduced by #587 where Take Now fails due to an existing `groupProgress` entry being missing when requesting to restart the activity/flow. This change makes the restart actions more forgiving by not assuming an existing `groupProgress` entry exists.
1. Perform **Take Now** on an activity.
**Expected outcome:** The web app proceeds to load the activity and allow you to submit it.
2. Perform **Take Now** on a flow.
**Expected outcome:** The web app proceeds to load the flow and allow you to submit it.
=> fix: Support restart action when not yet started (M2-8950)

.husky/pre-commit, .lintstagedrc.json, package.json, src/entities/activity/lib/types/item.ts, src/widgets/Survey/model/validateItem.test.ts, yarn.lock
🔗 [Jira Ticket M2-9059](https://mindlogger.atlassian.net/browse/M2-9059)
This PR adds updates to `RequestHealthRecordData` to be a skippable item.
A separate update to the current development flow was also included, adding the `lint-staged` package to the project, updating the current Husky pre-commit hook flow which consists of 4 steps:
1. Lint
2. Format
3. Test
4. Build
After this PR, the first 2 steps are handled by lint-staged, and the 2 last steps are removed from the hook and only handled within the repo's CI GitHub action workflow.
https://github.com/user-attachments/assets/898d05fd-3323-4c16-870b-fb9a0c6df305
To test this feature, an activity with an EHR item should exist and it should have the "Skippable Item" option turned on. In order to achieve this, three things must be true: …
=> feat: Update RequestHealthRecordData to be skippable (M2-9059)

src/shared/ui/Items/SelectBase/SelectBaseBox.tsx
🔗 [Jira Ticket M2-8988](https://mindlogger.atlassian.net/browse/M2-8988)
This PR adds a simple fix to an issue that was causing extra whitespace to be rendered in some components' test IDs.
A simple `trim()` prevents extra whitespace from being rendered when the conditional test id assignment returns `undefined`.
This was causing some tests to fail, so running the whole test suite successfully, without any issues related to whitespace or missmatched test ids, should work as a clear indicator this specific issue is solved.
=> fix: Remove unwanted whitespace in component test id (M2-8988)

src/entities/activity/lib/downloadPhrasalTemplateItem.ts, src/entities/activity/ui/items/PhrasalTemplateItem.tsx
🔗 [Jira Ticket M2-9181](https://mindlogger.atlassian.net/browse/M2-9181)
This PR fixes an error on Chrome iOS with the action plan download button. When users click the download button, this error is thrown:
```
Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
```
I assume that recent updates to Chrome have made it more finicky to trigger file downloads, and it seems that doing so inside an async function is problematic. This PR fixes that by doing a couple things:
- Converting the callback to a regular non-async function
- Pre-rendering the image(s) for download on mobile
- Not awaiting the call to the download function on desktop (as a consequence of the first …
=> fix: Problems saving phrase-builder action plan on mobile browser (M2-9181)

package.json, yarn.lock
🔗 [Jira Ticket M2-9142](https://mindlogger.atlassian.net/browse/M2-9142)
This PR updates the `axios` entry in the `package.json` file to `^1.8.2`, up from `^1.7.7`. As at today, this will install version 1.9.0 and the `yarn.lock` file has also been updated to reflect that.
I've performed the following verification steps to build confidence that this doesn't break anything:
N/A
Poke it and see if it breaks
N/A
=> chore: Upgrade axios to ^1.8.2 (M2-9142)

.github/workflows/update-jira-tickets.yaml
🔗 [Jira Ticket M2-9292](https://mindlogger.atlassian.net/browse/M2-9292)
This change makes room for a `JIRA_WEBHOOK_SECRET` value in the webhook call to Jira. This is necessary because Jira recently updated their webhook URL to one that requires a secret header.
To complete this change, we need to do the following:
If you really want to test this, you can contact me for the values mentioned above, then make the curl call with:
- The old URL, and an empty value for the secret header
- The new URL and the valid secret value
N/A
=> chore: Include JIRA_WEBHOOK_SECRET in webhook call (M2-9292)

src/entities/applet/model/slice.ts, src/entities/applet/model/types.ts, src/pages/NavigateToActiveAssessment/NavigateToActiveAssessment.test.tsx, src/pages/NavigateToActiveAssessment/index.tsx, src/widgets/Survey/model/hooks/useSubSteps/useSubSteps.test.tsx, src/widgets/Survey/model/hooks/useSubSteps/useSubSteps.ts, src/widgets/Survey/model/hooks/useSurveyState.ts
🔗 [Jira Ticket M2-9269](https://mindlogger.atlassian.net/browse/M2-9269)
Fixes an issue whereby you can't proceed within the substeps of an EHR item – or proceed past it to any subsequent item and complete the assessment – if one or more items preceding the EHR item type are configured as hidden.
1. Create an applet with an activity containing at least two items:
- 1st item can be any item type, and should be hidden
- 2nd item should be an EHR item
2. Start the activity in the Web App.
3. Click the “opt in” option on the EHR item type.
4. Click Next.
**Expected outcome:** You're able to proceed past the consent step to the partnership step and share EHR data, and complete the assessment.
=> fix: Hidden item before EHR item type (M2-9269)

src/widgets/InactivityTracker/InactivityTracker.tsx
🔗 [Jira Ticket M2-9446](https://mindlogger.atlassian.net/browse/M2-9446)
This PR just adds a dependency array to the useEffect in the InactivityTracker. The lack of a dependency array caused the `IdleTimer.createListener` callback to be using an outdated version of the `logout` function, which has a reference to the URL that existed when the page first loaded.
https://github.com/user-attachments/assets/d5718b3e-82fb-4730-9fb1-19f030879de5
https://github.com/user-attachments/assets/fc67da6c-5194-4cbd-9ec2-faede9826c8a
1. Temporarily edit the file [InactivityTracker.tsx:19](https://github.com/ChildMindInstitute/mindlogger-web-refactor/blob/98979e1b648774c9cf0bda3f738eea3189c0de59/src/widgets/InactivityTracker/InactivityTracker.tsx#L19) and set it to 1 minute to make testing easier
2. Create …
=> fix: Inactivity Tracker logout memoization (M2-9446)

README.md
🔗 [Jira Ticket M2-9650](https://mindlogger.atlassian.net/browse/M2-9650)
This PR updates the README to include:
- Installation instructions for `nvm`
- Configuration steps for loading `nvm` in terminal shells
- An explanation of why configuring `nvm` is necessary for local development
=> docs: Add nvm setup instructions to README (M2-9650)
