ChildMindInstitute/mindlogger-web-refactor

src/app/Layout.tsx, src/app/Main.tsx, src/widgets/Header/index.ts, src/widgets/Header/lib/useNavbarTranslation.ts, src/widgets/Header/ui/LoginButton.tsx, src/widgets/Header/ui/header.scss, src/widgets/Header/ui/index.tsx
Not linked to a task. Just refactor things. 
Change file names with case sensitive rules.
=> Refactor: update file names

Jenkinsfile.groovy
Added Jenkinsfile to trigger auto build/deployment.
=> added Jenkinsfile

src/entities/activity/lib/types/item.ts, src/entities/activity/ui/ActivityCardItem.tsx, src/entities/activity/ui/ActivityCardItemList.tsx, src/entities/activity/ui/ActivityItemStepper.tsx, src/entities/activity/ui/ActivityOnePageAssessment.tsx, src/entities/activity/ui/ItemCardButtons.tsx, src/pages/Thanks/index.tsx, src/pages/Thanks/style.scss, src/pages/index.tsx, src/shared/utils/routes/constants.ts, src/widgets/ActivityDetails/ui/ActivityItemList.tsx
M2-1220 (Confirmation popup)
M2-1221 (Thanks page)
Navigator buttons fixes
=> feature: confirmation popup UI

html-scripts.js, index.html, package.json, yarn.lock
https://mindlogger.atlassian.net/browse/M2-2354
=> feat(analytics): Added Freshpaint integration

index.html, src/entities/activity/lib/constants.ts, src/entities/activity/lib/types/activityGroupBuilder.ts, src/entities/activity/lib/types/item.ts, src/entities/activity/model/activityBuilder.ts, src/entities/activity/model/types.ts, src/entities/activity/ui/ActivityCardItem.tsx, src/entities/activity/ui/items/ItemPicker.tsx, src/shared/api/types/activity.ts, src/shared/api/types/item.ts, src/shared/ui/CardItem/CardItem.tsx, src/shared/ui/CardItem/style.scss, src/widgets/ActivityDetails/model/mappers.ts, src/widgets/ActivityDetails/model/validateItemsBeforeSubmit.ts, src/widgets/ActivityDetails/ui/ActivityItemList.tsx, src/widgets/ActivityGroups/model/factories/ActivityGroupsBuilder.ts, src/widgets/ActivityGroups/ui/ActivityGroupList.tsx
Reverts ChildMindInstitute/mindlogger-web-refactor#148
=> Revert "[M2-2568] Feature: message item type implemented"

index.html, src/entities/activity/lib/constants.ts, src/entities/activity/lib/types/activityGroupBuilder.ts, src/entities/activity/lib/types/item.ts, src/entities/activity/model/activityBuilder.ts, src/entities/activity/model/types.ts, src/entities/activity/ui/ActivityCardItem.tsx, src/entities/activity/ui/ItemCardButtons.tsx, src/entities/activity/ui/items/ItemPicker.tsx, src/shared/api/types/activity.ts, src/shared/api/types/item.ts, src/shared/ui/CardItem/CardItem.tsx, src/shared/ui/CardItem/style.scss, src/widgets/ActivityDetails/model/mappers.ts, src/widgets/ActivityDetails/model/validateItemsBeforeSubmit.ts, src/widgets/ActivityDetails/ui/ActivityItemList.tsx, src/widgets/ActivityGroups/model/factories/ActivityGroupsBuilder.ts, src/widgets/ActivityGroups/ui/ActivityGroupList.tsx
=> Feature: M2-2568

src/entities/activity/lib/markdownVariableReplacer.ts
https://mindlogger.atlassian.net/browse/M2-3774
=> fix(markdown): Added preprocessor that removes redundant postfix from image links

src/widgets/ActivityGroups/lib/activityGroupsBuilder.ts, src/widgets/ActivityGroups/lib/types.ts, src/widgets/ActivityGroups/model/factories/ActivityGroupsBuilder.test.ts, src/widgets/ActivityGroups/model/factories/AvailableGroupBuilder.test.ts, src/widgets/ActivityGroups/model/factories/ListItemsFactory.ts, src/widgets/ActivityGroups/model/factories/ScheduledGroupEvaluator.test.ts, src/widgets/ActivityGroups/model/hooks/useEntityCardDetails.ts, src/widgets/ActivityGroups/model/mappers.ts, src/widgets/ActivityGroups/ui/ActivityCard/index.tsx
Resolve: [M2-4733](https://mindlogger.atlassian.net/browse/M2-4733)
[M2-4733]: https://mindlogger.atlassian.net/browse/M2-4733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [M2-4733] Fix 2.5:  Hide Badge settings for Activity Flow

src/widgets/ActivityGroups/model/factories/ActivityGroupsBuilder.test.ts, src/widgets/ActivityGroups/model/factories/ListItemsFactory.ts, src/widgets/ActivityGroups/ui/ActivityCard/TimeStatusLabel.tsx
Resolve: [M2-3443](https://mindlogger.atlassian.net/browse/M2-3443)
[M2-3443]: https://mindlogger.atlassian.net/browse/M2-3443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [M2-3443] Fix-2.5: due info for inProgress cards

src/shared/ui/Items/AudioPlayer/ui/AudioPlayerBase.tsx, src/shared/ui/Items/AudioPlayer/ui/AudioPlayerControls.tsx, src/shared/ui/Items/AudioPlayer/ui/AudioPlayerDuration.tsx, src/shared/ui/Items/AudioPlayer/ui/AudioPlayerVolume.tsx, src/shared/ui/Items/AudioPlayer/ui/AudipPlayerProgressBar.tsx
Resolve: [M2-4857](https://mindlogger.atlassian.net/browse/M2-4857)
[M2-4857]: https://mindlogger.atlassian.net/browse/M2-4857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [M2-4857] Tests: audio player

src/shared/ui/Markdown/lib/Vimeo.builder.test.ts, src/shared/ui/Markdown/lib/Vimeo.builder.ts, src/shared/ui/Markdown/lib/YouTube.builder.test.ts, src/shared/ui/Markdown/lib/YouTube.builder.ts, src/shared/ui/Markdown/lib/markdown-builder.ts, src/shared/ui/Markdown/style.css, src/shared/utils/helpers/getInitials.ts
Resolve: [M2-4774](https://mindlogger.atlassian.net/browse/M2-4773)
Resolve: [M2-4887](https://mindlogger.atlassian.net/browse/M2-4887)
[M2-4774]: https://mindlogger.atlassian.net/browse/M2-4774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[M2-4887]: https://mindlogger.atlassian.net/browse/M2-4887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [M2-4773][M2-4887] Fix-2.5: Youtube Videos, Images, Videos supports in WYSIWYG

src/i18n/en/translation.json, src/i18n/fr/translation.json, src/shared/ui/BaseButton/index.tsx, src/shared/ui/BootstrapModal/index.tsx, src/shared/ui/MuiModal/index.tsx, src/shared/ui/index.ts, src/widgets/ActivityDetails/ui/AssessmentPassingScreen.tsx, src/widgets/ActivityGroups/ui/ActivityGroupList.tsx
Resolve: [M2-4788](https://mindlogger.atlassian.net/browse/M2-4788)
[M2-4788]: https://mindlogger.atlassian.net/browse/M2-4788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [M2-4788] Feature: "Next" button behavior update

src/entities/activity/lib/types/item.ts, src/entities/activity/ui/items/CheckboxItem/index.tsx, src/shared/api/types/item.ts
Resolve: [M2-5048](https://mindlogger.atlassian.net/browse/M2-5048)
[M2-5048]: https://mindlogger.atlassian.net/browse/M2-5048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [M2-5048] Feature: isNoneAbove for MultiSelectItem

src/entities/activity/ui/items/AudioPlayerItem.tsx, src/entities/activity/ui/items/ItemPicker.tsx, src/entities/applet/model/mapper.ts, src/entities/applet/model/types.ts, src/i18n/en/translation.json, src/i18n/fr/translation.json, src/shared/api/types/activity.ts, src/shared/ui/Items/AudioPlayer/lib/constants.ts, src/shared/ui/Items/AudioPlayer/lib/index.ts, src/shared/ui/Items/AudioPlayer/ui/AudioPlayerBase.tsx, src/widgets/ActivityDetails/model/mappers.ts, src/widgets/ActivityDetails/model/validateItem.ts
[M2-5022](https://mindlogger.atlassian.net/browse/M2-5022) - preventing user to skip the audio player if it is not skippable
[M2-5025](https://mindlogger.atlassian.net/browse/M2-5025) - added value to audio Item 
[M2-5022]: https://mindlogger.atlassian.net/browse/M2-5022?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[M2-5025]: https://mindlogger.atlassian.net/browse/M2-5025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> M2-5022: preventing user to skip the audio player if it is not skippable

src/entities/activity/ui/items/CheckboxItem/index.tsx
Resolve: [M2-5048](https://mindlogger.atlassian.net/browse/M2-5048)
Fixes as per requirements. (https://github.com/ChildMindInstitute/mindlogger-web-refactor/pull/364/files#r1477864972)
[M2-5048]: https://mindlogger.atlassian.net/browse/M2-5048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixed isNoneAbove business logic

LICENSE.md, README.md
🔗 [Jira Ticket M2-5376](https://mindlogger.atlassian.net/browse/M2-5376)
This PR copies the `LICENSE.md` file from the original web app to the refactored version.
=> M2-5376: add `LICENSE.md`

src/widgets/ActivityGroups/ui/ActivityCard/index.tsx
resolves: M2-4993
Mixpanel tracking improvements. I have been added two new events to track when user resume or restart activity.
=> M2-4993 Mixpanel Tracking: Assessment Resume/Restart

src/shared/utils/analytics/analyticsService.ts, src/widgets/ActivityDetails/model/hooks/useSubmitAnswersMutation.ts
resolves: M2-5033
SubmitId was added to some events for analytic enhancement. 
_List of events:_
[Web] Assessment completed
=> M2-5033 [Web] Mixpanel Tracking: Sumbit_id in event properties

Jenkinsfile.groovy
No task was created. Jenkins update
=> [No-task] Jenkins update

src/features/ForgotPassword/ui/ForgotPasswordForm.tsx
resolves: M2-3613
Reuse base button on the Forgot Password Page.
=> M2-3613 Button height

src/pages/Profile/index.tsx, src/pages/Settings/index.tsx, src/shared/ui/Dropdown/ui/index.tsx, src/widgets/Footer/index.tsx
resolves: M2-3614
Change font from the Roboto (old font) to Atkinson (new font)
=> M2-3614 Change dropdown font from Roboto to Atkinson

src/entities/activity/ui/ItemCardButtons.tsx
=> Fix button width on the assessment page

.github/pull_request_template.md, src/abstract/lib/GroupBuilder/AvailableGroupBuilder.test.ts, src/abstract/lib/GroupBuilder/AvailableGroupEvaluator.ts, src/abstract/lib/GroupBuilder/GroupUtility.ts, src/abstract/lib/GroupBuilder/ScheduledGroupEvaluator.test.ts, src/entities/activity/ui/ItemCardButtons.tsx, src/entities/event/model/operations/ScheduledDateCalculator.monthly.test.ts, src/entities/event/model/operations/ScheduledDateCalculator.ts, src/features/ForgotPassword/ui/ForgotPasswordForm.tsx, src/pages/Profile/index.tsx, src/pages/Settings/index.tsx, src/shared/constants/routes.ts, src/shared/ui/Dropdown/ui/index.tsx, src/shared/ui/Markdown/lib/markdown-builder.ts, src/shared/ui/Markdown/lib/validateAudio.ts, src/shared/ui/Markdown/style.css, src/widgets/Footer/index.tsx
=> Merge changes from the release/2.1.2 to the main

src/features/Signup/ui/SignupForm.tsx, src/shared/ui/BaseButton/index.tsx, src/shared/ui/Card/index.tsx, src/shared/ui/Input/index.tsx, src/shared/ui/Text/index.tsx, src/widgets/Header/ui/LoginButton.tsx
🔗 [Jira Ticket M2-3614](https://mindlogger.atlassian.net/browse/M2-3614)
Small changes to make all components with the same font.
- Login page was updated
- Signup page was updated
- Login button in the header was updated
- Applet card was updated
=> [M2-3614] Change all component`s font to Atkinson

src/pages/ForgotPassword/index.tsx
🔗 [Jira Ticket M2-3614](https://mindlogger.atlassian.net/browse/M2-3614)
Change the font on the reset password page.
- Title on the reset password page
=> [M2-3614] Fix font on the Reset Password page

src/env.d.ts, src/shared/utils/analytics/mixpanel.ts
🔗 [Jira Ticket M2-6058](https://mindlogger.atlassian.net/browse/M2-6058)
Enable mixpanel for UAT env
=> [M2-6058] Enable mixpanel for UAT env

src/shared/ui/Items/Slider/index.tsx
🔗 [Jira Ticket M2-6081](https://mindlogger.atlassian.net/browse/M2-6081)
Change the logic how to highlight the selected value
=> [M2-6081] Change the logic how to highlight the selected value

src/shared/ui/Items/Slider/index.tsx
🔗 [Jira Ticket M2-6080](https://mindlogger.atlassian.net/browse/M2-6080)
- Data-testid attributes for slider
=> [M2-6080] Added data-testid attributes for slider component

src/entities/activity/ui/items/Matrix/MatrixMultiSelectItem/CheckboxButton.tsx, src/entities/activity/ui/items/Matrix/MatrixRow.tsx, src/entities/activity/ui/items/Matrix/MatrixSingleSelectItem/RadioGrid.tsx, src/entities/activity/ui/items/Matrix/MatrixSingleSelectItem/index.tsx, src/shared/ui/Items/SelectBase/SelectBaseBox.tsx, src/widgets/ActivityDetails/model/mappers.ts, src/widgets/ActivityDetails/model/validateItem.ts, yarn.lock
🔗 [Jira Ticket M2-6147](https://mindlogger.atlassian.net/browse/M2-6147)
🔗 [Jira Ticket M2-6148](https://mindlogger.atlassian.net/browse/M2-6148)
- [Thing]
- [Other thing]
- [More things]
=> [M2-6147] [M2-6148] Yarn.lock was optimised by vite

src/entities/activity/ui/items/Matrix/MatrixMultiSelectItem/CheckboxButton.tsx, src/entities/activity/ui/items/Matrix/MatrixRow.tsx, src/entities/activity/ui/items/Matrix/MatrixSingleSelectItem/RadioGrid.tsx, src/entities/activity/ui/items/Matrix/MatrixSingleSelectItem/index.tsx, src/shared/ui/Items/SelectBase/SelectBaseBox.tsx, src/widgets/ActivityDetails/model/mappers.ts, src/widgets/ActivityDetails/model/validateItem.ts, yarn.lock
🔗 [Jira Ticket M2-6147](https://mindlogger.atlassian.net/browse/M2-6147)
🔗 [Jira Ticket M2-6148](https://mindlogger.atlassian.net/browse/M2-6148)
=> [M2-6148] [M2-6147] Fixes for SingleSelectionPerRow and MultiSelectionPerRow

yarn.lock
I have catch a bug with incorrect deps. And vite --force doesn`t help. I have resolved this issue by removing yarn.lock and reinstalling all deps.
=> The yarn.lock file was updated by vite

src/widgets/ActivityDetails/model/mappers.ts
🔗 [Jira Ticket M2-6290](https://mindlogger.atlassian.net/browse/M2-6290)
This PR includes the alert mappers for Matrix items. Now alerts work correctly for the following items: SliderRows, SingleSelectRows, MultiSelectRows
=> [M2-6290] Fix: Alerts for Matrix items

src/entities/activity/ui/items/Matrix/MatrixCell.tsx, src/shared/ui/Items/SelectBase/SelectBaseBox.tsx
🔗 [Jira Ticket M2-6147](https://mindlogger.atlassian.net/browse/M2-6147)
=> [M2-6147] Fix: SelectBaseBox styles

src/widgets/ActivityDetails/model/mappers.ts
🔗 [Jira Ticket M2-6549](https://mindlogger.atlassian.net/browse/M2-6549)
Before submitting the answers some logic processing the data related to alerts. This logic had a bug.
- Alert mappers
=> fix(matrix): Adding alerts data in the answer while submitting (M2-6549)

src/entities/applet/model/hooks/useMultiInformantState.ts, src/features/TakeNow/ui/ValidateTakeNowParams.tsx, src/widgets/ActivityDetails/model/hooks/useAnswers.ts
🔗 [Jira Ticket M2-6534](https://mindlogger.atlassian.net/browse/M2-6534)
One of the new features includes state changes but at some specific moments, the application had the old version of the state. Guard was added to validate that the required state exists.
- Multiinformant feature
=> hotfix(state-access): Guards was added

src/widgets/ActivityDetails/ui/AssessmentPassingScreen.tsx
🔗 [Jira Ticket M2-6765](https://mindlogger.atlassian.net/browse/M2-6765)
This fix is only for auto tests
- Guard before accessing the scoreAndReport settings
=> (fix: M2-6765)A guard was added before accessing to the scoresAndReports settings

src/features/PassSurvey/ui/SummaryScreen/Alerts.tsx, src/features/PassSurvey/ui/SummaryScreen/ScoreSection.tsx, src/features/PassSurvey/ui/SummaryScreen/Scores.tsx, src/features/PassSurvey/ui/SummaryScreen/index.tsx, src/widgets/ActivityDetails/ui/AssessmentSummaryScreen.tsx
🔗 [Jira Ticket M2-6805](https://mindlogger.atlassian.net/browse/M2-6805)
=> (feat: M2-6805) The summary screen data-testids coverage

src/entities/activity/lib/types/item.ts, src/entities/applet/model/hooks/index.ts, src/entities/applet/model/hooks/useActivityProgress.ts, src/entities/applet/model/hooks/useItemTimerState.ts, src/entities/applet/model/integrations/AppletIntegrationsService.ts, src/entities/applet/model/integrations/LorisAppletIntegration.ts, src/entities/applet/model/slice.ts, src/entities/applet/model/types.ts, src/features/PassSurvey/hooks/index.ts, src/features/PassSurvey/hooks/useItemTimer.ts, src/features/PassSurvey/lib/canItemHaveTimer.ts, src/features/PassSurvey/lib/index.ts, src/features/PassSurvey/model/ScoresCalculator.ts, src/features/PassSurvey/ui/ItemTimerBar.tsx, src/features/PassSurvey/ui/SurveyManageButtons.tsx, src/shared/api/types/item.ts, src/shared/utils/convert/date/index.ts, src/shared/utils/convert/date/msToMinSec.ts, src/shared/utils/index.ts, src/shared/utils/useTimer.ts, src/widgets/ActivityDetails/ui/AssessmentLayout.tsx, src/widgets/ActivityDetails/ui/AssessmentLayoutFooter.tsx, src/widgets/ActivityDetails/ui/AssessmentPassingScreen.tsx, src/widgets/ActivityGroups/model/hooks/useIntegrationsSync.ts, src/widgets/ProtectedRoute/InactivityTracker.tsx
🔗 [Jira Ticket M2-5678](https://mindlogger.atlassian.net/browse/M2-5678)
The admin panel has timer settings for each item. This setting limit time that user have to give a answer. This "pr" includes item timer implementation.
- useTimer
- useItemTimerState
- useItemTimer
- AssessmentPassingScreen
=> (feat: M2-5678) Item-level timer

src/features/PassSurvey/ui/StartAssessmentButton.tsx, src/widgets/ActivityDetails/ui/AssessmentPassingScreen.tsx
🔗 [Jira Ticket M2-6773](https://mindlogger.atlassian.net/browse/M2-6773)
An empty Summary screen is shown if the 'Show Score Summary 'checkbox = True but no Scores or Alerts have been configured
- onAnswerSuccessSubmit handler
=> (fix: M2-6773) Empty Summary screen is shown if 'Show Score Summary 'checkbox = True but no Scores or Alerts has been configured

src/widgets/Survey/model/hooks/useAnswers.ts
🔗 [Jira Ticket M2-6988](https://mindlogger.atlassian.net/browse/M2-6988)
Fix the condition for isDataShare property
=> (fix: M2-6988) Loris integration

src/shared/api/types/applet.ts, src/widgets/Survey/model/hooks/useAnswers.ts, src/widgets/Survey/ui/PassingScreen.tsx
🔗 [Jira Ticket M2-6988](https://mindlogger.atlassian.net/browse/M2-6988)
=> (fix: M2-6988) Fix: 422 error for applets with disabled loris integration

src/widgets/Survey/model/hooks/useAnswers.ts
🔗 [Jira Ticket M2-6988](https://mindlogger.atlassian.net/browse/M2-6988)
=> (fix: M2-6988) fix: 422 extra field in body

src/shared/api/types/activity.ts, src/widgets/Survey/model/hooks/useAnswers.ts
🔗 [Jira Ticket M2-#](https://mindlogger.atlassian.net/browse/M2-#)
- [Thing]
- [Other thing]
- [More things]
| Before (Optional)                      | After                                 |
| -------------------------------------- | ------------------------------------- |
|  |  |
=> (no-task) Change isDataShare flag to consentToShare

src/features/PassSurvey/model/AnswersConstructService.ts
🔗 [Jira Ticket M2-7181](https://mindlogger.atlassian.net/browse/M2-7181)
=> (fix: M2-7181) Incorrect Answer DTO

src/widgets/Survey/ui/PassingScreen.tsx, src/widgets/Survey/ui/WelcomeScreen.tsx
🔗 [Jira Ticket M2-7187](https://mindlogger.atlassian.net/browse/M2-7187)
=> (fix: M2-7187) The Summary screen is displayed after 1 activity out of 3 from the Activity Flow (Respondent is blocked to continue the assessment)

src/features/PassSurvey/ui/EntityTimer.tsx, src/features/PassSurvey/ui/SurveyHeader.tsx, src/features/PassSurvey/ui/SurveyLayout.tsx, src/widgets/Survey/ui/PassingScreen.tsx, src/widgets/Survey/ui/WelcomeScreen.tsx
🔗 [Jira Ticket M2-7147](https://mindlogger.atlassian.net/browse/M2-7147)
The entityTimer UI was integrated into the Survey Header. The UI was created for desktop and mobile devices. The UI was integrated but disabled for this PR. It`s going to be enabled in the future PR.
=> (feat: M2-7147)The EntityTimer UI was integrated into the Survey Header

src/features/PassSurvey/helpers/mappers.ts
🔗 [Jira Ticket M2-6297](https://mindlogger.atlassian.net/browse/M2-6297)
[Web, Data Export] There is unexpected record in report.csv for skipped on web slider row item
=> (fix: M2-6297) The mapper for SliderRowAnswer was fixed

src/widgets/Survey/ui/ActivityMetaData.tsx, src/widgets/Survey/ui/WelcomeScreen.tsx
🔗 [Jira Ticket M2-7202](https://mindlogger.atlassian.net/browse/M2-7202)
=> (fix: M2-7202) The calculcation logic of meta data about flow was changed

src/i18n/en/translation.json, src/i18n/fr/translation.json, src/widgets/Survey/ui/WelcomeScreen.tsx
🔗 [Jira Ticket M2-7353](https://mindlogger.atlassian.net/browse/M2-7353)
=> (fix: M2-7353) Fixed the welcome screen for a timed activity

src/features/AutoCompletion/model/extractActivityidsToSubmitByParams.test.ts, src/i18n/en/translation.json, src/i18n/fr/translation.json, src/widgets/AutoCompletion/ui/AutoCompletionScreen.tsx, src/widgets/InactivityTracker/InactivityTracker.tsx, src/widgets/InactivityTracker/lib/useIdleTimer.ts, src/widgets/Survey/ui/PassingScreen.tsx
🔗 [Jira Ticket M2-7581](https://mindlogger.atlassian.net/browse/M2-7581)
🔗 [Jira Ticket M2-7592](https://mindlogger.atlassian.net/browse/M2-7592)
🔗 [Jira Ticket M2-7353](https://mindlogger.atlassian.net/browse/M2-7353)
=> (fix: M2-7581) Available activity starts not from the beginning after Idle Timer ends

package.json, yarn.lock
🔗 [Jira Ticket M2-7725](https://mindlogger.atlassian.net/browse/M2-7725)
- Upgrade Axios
=> [M2-7725] Upgrade deps #2: Axios

src/features/PassSurvey/ui/EntityTimer.tsx, src/features/PassSurvey/ui/ItemTimerBar.tsx, src/features/Signup/ui/SignupForm.tsx, src/i18n/en/translation.json, src/i18n/fr/translation.json, src/widgets/AppletList/index.tsx, src/widgets/Survey/ui/ActivityMetaData.tsx
Removed a few hardcoded strings found in the web app.
🔗 [Jira Ticket M2-8179](https://mindlogger.atlassian.net/browse/M2-8179)
| Before (Optional)                      | After                                 |
| -------------------------------------- | ------------------------------------- |
| ![CleanShot 2024-11-07 at 16 49 42](https://github.com/user-attachments/assets/1d14db1c-b861-41c9-82ce-f804b1d694fa) | ![CleanShot 2024-11-07 at 16 49 27](https://github.com/user-attachments/assets/42445505-605b-4317-88ea-7d8a58e7a042) |
- Go to Create Account
- Change language between English and French. "I agree to the Terms and Conditions" should translate
- Log in to a new, empty account and see "No applets"
Greek is not translated on purpose, these will be provided by the translation vendor and …
=> fix: remove hardcoded strings

src/features/TakeNow/ui/TakeNowSuccessModal.tsx
=> Release/v2.5.1 [dev]

.github/workflows/ci.yml
This PR adds a build item to the CI checklist, to act as a clear indicator to the assignee and reviewer whether the code will build successfully.
Pay attention to the execution of the build step
N/A
=> chore: Add a build step to CI

package.json
Merge `release/2025.02.2` -> main
=> Release/2025.02.2 [main]

package.json, src/entities/activity/lib/downloadPhrasalTemplateItem.ts, src/entities/activity/ui/items/PhrasalTemplateItem.tsx, yarn.lock
Merging `release/2025.05.3` to main
=> Release/2025.05.3 [main]

.github/workflows/run_build_deploy_uat.yaml
🔗 [Jira Ticket M2-9644](https://mindlogger.atlassian.net/browse/M2-9644)
- UAT build job
=> chore: Adding build job for UAT
